version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run :
          name: Install Maven
          command: |
            sudo apt install maven
      - run:
          name: Build WAR
          command: |
            cd email/
            mvn package
            cd target
            ls -al
            pwd
      # - run:
      #     name: Zip Artifact
      #     command: |
      #       echo "Hello the current build number is ${CIRCLE_BUILD_NUM}"
      #       pwd
      #       ls -al
      #       mkdir -p lambda_artifact
      #       pwd
      #       ls -al
      #       mv webapp/target/email-1.0-SNAPSHOT.jar lambda_artifact/
      #       ls -al
      #       cd lambda_artifact
      #       ls -al
      #       pwd
      #       cd ..
      #       pwd
      #       ls -al
      - run:
          name: Install pip
          command: |
            sudo apt-get update || sudo apt-get update
            sudo apt-get install python3
            python3 --version
            sudo apt install python3-pip
            pip3 --version
      - run:
          name: AWS CLI Install 
          command: sudo pip3 install awscli
      - run:
          name: Upload Artifact To S3
          command: |            
            echo "Uploading to S3 bucket"
            # cd lambda_artifact
            # aws s3 cp email-1.0-SNAPSHOT.jar s3://${AWS_CODE_DEPLOY_BUCKET}
            aws s3 cp email-1.0-SNAPSHOT.jar s3://${AWS_CODE_DEPLOY_BUCKET}
      # - run :
      #     name : Updating Lambda Function 
      #     command : |
      #       aws lambda update-function-code --region=${REGION} \
      #       --function-name=csye6225_summer2019 \
      #       --zip-file fileb://target/email-1.0-SNAPSHOT.zip
